# java -jar target/xxx.war --spring.profiles.active=prod
spring:
  profiles:
    # application-后文件名
    active: dev

  # 全局json序列化不为null的属性
  jackson:
    default-property-inclusion: non_null

# xml路径
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

other:
  aaa: 111
  bbb: 222
  ccc: "aaa: ${other.aaa}, bbb: ${other.bbbValue}"
