# java -jar target/xxx.war --spring.profiles.active=prod
spring:
  profiles:
    # application-后文件名
    active: dev

  # 全局json序列化不为null的属性
  jackson:
    default-property-inclusion: non_null

# logback简单配置: 日志文件路径、日志输出格式
#logging:
#  pattern:
#    # 控制台日志格式: %d: date, %msg: 日志信息, %n: 换行
#    console: "%d - %msg%n"
#  # 日志级别: error-40、warn-30、info-20、debug-10、trace-0
#  level: #debug
#    # 或指定到具体类的级别
#    com.nsntc.interview.logback.LoggerTest: debug
#  # 配置文件路径
#  config:
#  # 输出日志路径, 默认文件名为spring.log
#  path: /Users/wkmtem/development/tomcat-7.0.77/
#  # 输出日志文件名称,与path功能相同
#  file: /Users/wkmtem/development/tomcat-7.0.77/log.log


other:
  aaa: 111
  bbb: 222
  ccc: "aaa: ${other.aaa}, bbb: ${other.bbbValue}"